name: Go Forwarder

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/go-forwarder.yaml
      - go-forwarder/**

jobs:
  build_push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Build
        run: |
          GOARCH=amd64 go build -o build/x86_64
          GOARCH=arm64 go build -o build/aarch64
        working-directory: go-forwarder

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          context: go-forwarder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/menci/metricsnet/go-forwarder:latest
