name: Rathole

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/rathole.yaml
      - rathole/**

jobs:
  build_push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Copied from rathole's release.yaml
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Since rust 1.72, some platforms are tier 3
          toolchain: 1.71
          default: true
      - name: Add Rust target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Install cross
        run: cargo install --version 0.2.5 cross
      - name: Build x86_64
        run: cargo build --release --target=x86_64-unknown-linux-musl --features embedded --no-default-features
        working-directory: rathole/rathole
      - name: Build aarch64
        run: cross build --release --target=aarch64-unknown-linux-musl --features embedded --no-default-features
        working-directory: rathole/rathole

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          context: rathole
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/metricsnet/rathole:latest
