name: Tailscale

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/tailscale.yaml
      - tailscale/**

jobs:
  build_push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: tailscale/tailscale
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Apply Patches
        run: "git apply ../*.patch"
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Container Image
        run: "./build_docker.sh"
        env:
          PUSH: true
          REPOS: ghcr.io/menci/metricsnet/tailscale
